@startuml
'https://plantuml.com/sequence-diagram
entity User {
  * user_id : int <<PK>>
  --
  * email : varchar
  * password_hash : varchar
  * display_name : varchar
  * role : varchar
  * created_at : datetime
}

entity Board {
  * board_id : int <<PK>>
  --
  * name : varchar
  * description : text
  * created_at : datetime
}
@enduml